# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
#Answer using split()
s = "Hi there Sam!"
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
#Answer using format()
print("The diameter of {planet} is {diameter} kilometers".format(planet = "Earth",diameter = 12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [49]:
#Answer for grabbing word hello from nest dictionary
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])
       

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [24]:
#Array of 10 zeros
import numpy as np
n = np.zeros(10) 
n = n.astype(int) #to change number from decimal to integer
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#Array of 10 fives
import numpy as np
n = np.full(10,5)
n = n.astype(int) #to change number from decimal to integer
n

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [22]:
#Array with even integers from 20-35
import numpy as np
n = np.arange(20,35,2) #'2' for even splitting between numbers from '20-35'
n

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
#3x3 matrix ranging from 0-8
import numpy as np
n = np.arange(0,9).reshape(3,3) #arrage(0,9)- for values ranging from 0-8 & reshape(3,3)- for matrix shape as 3x3 
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [50]:
#Answer for a & b concatenation
import numpy as np
a = np.array([1,2,3]) #a
b = np.array([4,5,6]) #b
n = np.concatenate((a,b),axis=None) #axis=None for printing list in series
n

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [41]:
#DataFrame with 2 columns[even&odd] & rows[including odd and even numbers]
import pandas as pd
import numpy as np
myList = np.array([[2,3],[4,5],[6,7]]) #list containing odd and even number
myDataFrame = pd.DataFrame(myList,columns=["even","odd"]) #column name assigned as even and odd
myDataFrame

even  odd
0     2    3
1     4    5
2     6    7

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [43]:
#Dates from 1-January-2023 to 10-February-2023
import pandas as pd
date = pd.date_range(start='01-01-2023',end='10-02-2023')
for val in date: #to iterate dates ranging from jan to feb
  print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00
2023-02-11 00:00:00
2023-02-12 00:00:00
2023-02-13 00:00:00
2023-02-14 00:00:00
2023-02-15 00:00:00
2023-02-16 00:00:00
2023-02-17 00:00:00
2023-02-18 00:00:00
2023-02-19 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [51]:
#2D List to DataFrame
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25]]
myDataFrame = pd.DataFrame(lists) #List to DataFrame
myDataFrame

0    1   2
0  1  aaa  22
1  2  bbb  25